# docker-compose.yml
version: "3"
services:
  app:
    image: node:16
    restart: on-failure
    depends_on:
      - db
    working_dir: /app
    networks:
      - backend
    environment:
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGHOST: db
      PGDATABASE: ${POSTGRES_DB}
      PGPORT: 5432
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3005:3000"
    command: bash -c "npm install && npm run start"
    volumes:
      - .:/app/

  db:
    image: postgres:15
    networks:
      - backend
    ports:
      - "45432:5432"
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 25s
      timeout: 5s
      retries: 5
    hostname: db
    environment:
      PGUSER: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db-cli:/docker-entrypoint-initdb.d

networks:
  backend:
    driver: bridge